[build]
  publish = "exampleSite/public"
  command = "cd exampleSite && hugo --gc --themesDir ../.."

[build.environment]
  HUGO_VERSION = "0.57.2"
  HUGO_THEME = "repo"
  HUGO_BASEURL = "https://lil-boot-hugo-theme.netlify.com/"
