name = "Lil Boot"
license = "MIT"
licenselink = "TODO"
description = "TODO"
homepage = "https://github.com/zwbetz-gh/lil-boot-hugo-theme"
tags = ["TODO"]
features = ["TODO"]
min_version = "0.54.0"

[author]
  name = "Zachary Betz"
  homepage = "https://zwbetz.com/"
