baseURL: https://example.com
languageCode: en-us
defaultContentLanguage: en
title: Lil Boot
theme: lil-boot-hugo-theme

enableRobotsTXT: true
timeout: 45000

pygmentsCodefences: true
pygmentsStyle: pygments

googleAnalytics: UA-123456789-1
# disqusShortname: yourdiscussshortname

taxonomies:
  tag: tags

permalinks:
  post: /:filename/

imaging:
  quality: 90

params:
  # footer: Made with [Hugo](https://gohugo.io/). Themed by [Lil Boot](https://github.com/zwbetz-gh/lil-boot-hugo-theme). Hosted on [Netlify](https://www.netlify.com/).
  
menu:
  nav:
    - name: Home
      pre: >-
        <svg aria-hidden="true" xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" class="feather feather-home"><path d="M3 9l9-7 9 7v11a2 2 0 0 1-2 2H5a2 2 0 0 1-2-2z"></path><polyline points="9 22 9 12 15 12 15 22"></polyline></svg>
      url: /
      weight: 1
    - name: Blog
      pre: >-
        <svg aria-hidden="true" xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" class="feather feather-edit"><path d="M11 4H4a2 2 0 0 0-2 2v14a2 2 0 0 0 2 2h14a2 2 0 0 0 2-2v-7"></path><path d="M18.5 2.5a2.121 2.121 0 0 1 3 3L12 15l-4 1 1-4 9.5-9.5z"></path></svg>
      url: /post/
      weight: 2
    - name: Tags
      pre: >-
        <svg aria-hidden="true" xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" class="feather feather-tag"><path d="M20.59 13.41l-7.17 7.17a2 2 0 0 1-2.83 0L2 12V2h10l8.59 8.59a2 2 0 0 1 0 2.82z"></path><line x1="7" y1="7" x2="7" y2="7"></line></svg>
      url: /tags/
      weight: 3
    - name: RSS
      pre: >-
        <svg aria-hidden="true" xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" class="feather feather-rss"><path d="M4 11a9 9 0 0 1 9 9"></path><path d="M4 4a16 16 0 0 1 16 16"></path><circle cx="5" cy="19" r="1"></circle></svg>
      url: /index.xml
      weight: 4
